# =========================================================
# SMART NOTES MANAGEMENT SYSTEM
# PostgreSQL + Permanent PDF Storage
# =========================================================

from flask import (
    Flask,
    render_template,
    request,
    redirect,
    url_for,
    session,
    flash,
    send_file
)

import os
import io
import psycopg
from psycopg.rows import dict_row

from werkzeug.security import (
    generate_password_hash,
    check_password_hash
)

from werkzeug.utils import secure_filename


# =========================================================
# FLASK APP
# =========================================================

app = Flask(__name__)

app.secret_key = os.environ.get(
    "SECRET_KEY",
    "smart_notes_final_2026"
)


# =========================================================
# UPLOAD SETTINGS
# =========================================================

ALLOWED_EXTENSIONS = {"pdf"}


# =========================================================
# POSTGRESQL DATABASE
# =========================================================

DATABASE_URL = os.environ.get("DATABASE_URL")


def get_db():

    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL environment variable is not configured."
        )

    connection = psycopg.connect(
        DATABASE_URL,
        row_factory=dict_row
    )

    return connection


# =========================================================
# CHECK PDF
# =========================================================

def allowed_file(filename):

    return (
        "." in filename
        and filename.rsplit(".", 1)[1].lower()
        in ALLOWED_EXTENSIONS
    )


# =========================================================
# CREATE DATABASE TABLES
# =========================================================

def create_database():

    connection = get_db()

    try:

        # =====================================================
        # USERS TABLE
        # =====================================================

        connection.execute("""
            CREATE TABLE IF NOT EXISTS users (

                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                name TEXT NOT NULL,

                email TEXT UNIQUE NOT NULL,

                password TEXT NOT NULL,

                role TEXT NOT NULL DEFAULT 'student'

            )
        """)


        # =====================================================
        # NOTES TABLE
        # =====================================================

        connection.execute("""
            CREATE TABLE IF NOT EXISTS notes (

                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                title TEXT NOT NULL,

                subject TEXT NOT NULL,

                category TEXT NOT NULL,

                filename TEXT NOT NULL,

                uploaded_by TEXT NOT NULL,

                file_data BYTEA
            )
        """)


        # =====================================================
        # OLD NOTES TABLE COMPATIBILITY
        # =====================================================

        connection.execute("""
            ALTER TABLE notes
            ADD COLUMN IF NOT EXISTS file_data BYTEA
        """)


        # =====================================================
        # DEFAULT ADMIN
        # =====================================================

        admin_email = "admin@smartnotes.com"

        admin = connection.execute(
            """
            SELECT *
            FROM users
            WHERE email = %s
            """,
            (admin_email,)
        ).fetchone()


        if admin is None:

            admin_password = generate_password_hash(
                "admin123"
            )

            connection.execute(
                """
                INSERT INTO users
                (
                    name,
                    email,
                    password,
                    role
                )

                VALUES (%s, %s, %s, %s)
                """,
                (
                    "Administrator",
                    admin_email,
                    admin_password,
                    "admin"
                )
            )


        connection.commit()

    finally:

        connection.close()


# =========================================================
# DATABASE INITIALIZE
# =========================================================

create_database()


# =========================================================
# HOME
# =========================================================

@app.route("/")
def home():

    return render_template(
        "index.html"
    )


# =========================================================
# REGISTER
# =========================================================

@app.route(
    "/register",
    methods=["GET", "POST"]
)
def register():

    if request.method == "POST":

        name = request.form.get(
            "name",
            ""
        ).strip()

        email = request.form.get(
            "email",
            ""
        ).strip()

        password = request.form.get(
            "password",
            ""
        )


        # Empty field check

        if not name or not email or not password:

            flash(
                "Please fill all fields.",
                "error"
            )

            return redirect(
                url_for("register")
            )


        # Password length

        if len(password) < 6:

            flash(
                "Password must contain at least 6 characters.",
                "error"
            )

            return redirect(
                url_for("register")
            )


        connection = get_db()

        try:

            hashed_password = generate_password_hash(
                password
            )

            connection.execute(
                """
                INSERT INTO users
                (
                    name,
                    email,
                    password,
                    role
                )

                VALUES (%s, %s, %s, %s)
                """,
                (
                    name,
                    email,
                    hashed_password,
                    "student"
                )
            )

            connection.commit()

            flash(
                "Registration successful. Please login.",
                "success"
            )

            return redirect(
                url_for("login")
            )


        except psycopg.errors.UniqueViolation:

            connection.rollback()

            flash(
                "Email already registered.",
                "error"
            )

            return redirect(
                url_for("register")
            )


        finally:

            connection.close()


    return render_template(
        "register.html"
    )


# =========================================================
# LOGIN
# =========================================================

@app.route(
    "/login",
    methods=["GET", "POST"]
)
def login():

    if request.method == "POST":

        email = request.form.get(
            "email",
            ""
        ).strip()

        password = request.form.get(
            "password",
            ""
        )


        connection = get_db()

        try:

            user = connection.execute(
                """
                SELECT *
                FROM users
                WHERE email = %s
                """,
                (email,)
            ).fetchone()

        finally:

            connection.close()


        if user and check_password_hash(
            user["password"],
            password
        ):

            session["user_id"] = user["id"]

            session["user_name"] = user["name"]

            session["user_email"] = user["email"]

            session["user_role"] = user["role"]


            # Admin

            if user["role"] == "admin":

                return redirect(
                    url_for(
                        "admin_dashboard"
                    )
                )


            # Student

            return redirect(
                url_for(
                    "dashboard"
                )
            )


        flash(
            "Invalid email or password.",
            "error"
        )

        return redirect(
            url_for("login")
        )


    return render_template(
        "login.html"
    )


# =========================================================
# STUDENT DASHBOARD
# =========================================================

@app.route("/dashboard")
def dashboard():

    if "user_id" not in session:

        return redirect(
            url_for("login")
        )


    if session.get(
        "user_role"
    ) != "student":

        return redirect(
            url_for("admin_dashboard")
        )


    connection = get_db()

    try:

        total_notes = connection.execute(
            """
            SELECT COUNT(*) AS total
            FROM notes
            """
        ).fetchone()["total"]


        total_subjects = connection.execute(
            """
            SELECT COUNT(DISTINCT subject) AS total
            FROM notes
            """
        ).fetchone()["total"]


        important_notes = connection.execute(
            """
            SELECT COUNT(*) AS total
            FROM notes
            WHERE category = %s
            """,
            ("Important Questions",)
        ).fetchone()["total"]

    finally:

        connection.close()


    return render_template(
        "dashboard.html",

        name=session["user_name"],

        total_notes=total_notes,

        total_subjects=total_subjects,

        important_notes=important_notes
    )


# =========================================================
# ADMIN DASHBOARD
# =========================================================

@app.route("/admin")
def admin_dashboard():

    if "user_id" not in session:

        return redirect(
            url_for("login")
        )


    if session.get(
        "user_role"
    ) != "admin":

        return redirect(
            url_for("dashboard")
        )


    connection = get_db()

    try:

        students = connection.execute(
            """
            SELECT id, name, email
            FROM users
            WHERE role = %s
            ORDER BY id DESC
            """,
            ("student",)
        ).fetchall()


        notes = connection.execute(
            """
            SELECT
                id,
                title,
                subject,
                category,
                filename,
                uploaded_by
            FROM notes
            ORDER BY id DESC
            """
        ).fetchall()


        total_students = connection.execute(
            """
            SELECT COUNT(*) AS total
            FROM users
            WHERE role = %s
            """,
            ("student",)
        ).fetchone()["total"]


        total_notes = connection.execute(
            """
            SELECT COUNT(*) AS total
            FROM notes
            """
        ).fetchone()["total"]


        total_subjects = connection.execute(
            """
            SELECT COUNT(DISTINCT subject) AS total
            FROM notes
            """
        ).fetchone()["total"]

    finally:

        connection.close()


    return render_template(
        "admin.html",

        students=students,

        notes=notes,

        total_students=total_students,

        total_notes=total_notes,

        total_subjects=total_subjects,

        name=session["user_name"]
    )


# =========================================================
# UPLOAD NOTE
# =========================================================

@app.route(
    "/upload-note",
    methods=["POST"]
)
def upload_note():

    if "user_id" not in session:

        return redirect(
            url_for("login")
        )


    if session.get(
        "user_role"
    ) != "admin":

        flash(
            "Only admin can upload notes.",
            "error"
        )

        return redirect(
            url_for("dashboard")
        )


    title = request.form.get(
        "title",
        ""
    ).strip()


    subject = request.form.get(
        "subject",
        ""
    ).strip()


    category = request.form.get(
        "category",
        ""
    ).strip()


    file = request.files.get(
        "file"
    )


    # Empty field check

    if not title or not subject or not category:

        flash(
            "Please fill all note details.",
            "error"
        )

        return redirect(
            url_for("admin_dashboard")
        )


    # File check

    if not file or file.filename == "":

        flash(
            "Please select a PDF file.",
            "error"
        )

        return redirect(
            url_for("admin_dashboard")
        )


    # PDF check

    if not allowed_file(
        file.filename
    ):

        flash(
            "Only PDF files are allowed.",
            "error"
        )

        return redirect(
            url_for("admin_dashboard")
        )


    # Safe filename

    filename = secure_filename(
        file.filename
    )


    # =====================================================
    # READ PDF INTO MEMORY
    # =====================================================

    file_data = file.read()


    if not file_data:

        flash(
            "The selected PDF is empty.",
            "error"
        )

        return redirect(
            url_for("admin_dashboard")
        )


    # =====================================================
    # SAVE PDF + DETAILS IN POSTGRESQL
    # =====================================================

    connection = get_db()

    try:

        connection.execute(
            """
            INSERT INTO notes
            (
                title,
                subject,
                category,
                filename,
                uploaded_by,
                file_data
            )

            VALUES (%s, %s, %s, %s, %s, %s)
            """,
            (
                title,
                subject,
                category,
                filename,
                session["user_name"],
                psycopg.Binary(file_data)
            )
        )


        connection.commit()


        flash(
            "Notes uploaded successfully!",
            "success"
        )


    except Exception:

        connection.rollback()

        flash(
            "Error while uploading note.",
            "error"
        )


    finally:

        connection.close()


    return redirect(
        url_for("admin_dashboard")
    )


# =========================================================
# NOTES PAGE
# =========================================================

@app.route("/notes")
def notes():

    if "user_id" not in session:

        return redirect(
            url_for("login")
        )


    search = request.args.get(
        "search",
        ""
    ).strip()


    connection = get_db()

    try:

        if search:

            search_pattern = f"%{search}%"


            notes_data = connection.execute(
                """
                SELECT
                    id,
                    title,
                    subject,
                    category,
                    filename,
                    uploaded_by
                FROM notes

                WHERE title ILIKE %s
                   OR subject ILIKE %s
                   OR category ILIKE %s

                ORDER BY id DESC
                """,
                (
                    search_pattern,
                    search_pattern,
                    search_pattern
                )
            ).fetchall()


        else:

            notes_data = connection.execute(
                """
                SELECT
                    id,
                    title,
                    subject,
                    category,
                    filename,
                    uploaded_by
                FROM notes
                ORDER BY id DESC
                """
            ).fetchall()

    finally:

        connection.close()


    return render_template(
        "notes.html",

        notes=notes_data,

        search=search
    )


# =========================================================
# DOWNLOAD PDF
# =========================================================

@app.route(
    "/download/<int:note_id>"
)
def download(note_id):

    if "user_id" not in session:

        return redirect(
            url_for("login")
        )


    connection = get_db()

    try:

        note = connection.execute(
            """
            SELECT
                filename,
                file_data
            FROM notes
            WHERE id = %s
            """,
            (note_id,)
        ).fetchone()

    finally:

        connection.close()


    if not note:

        flash(
            "Note not found.",
            "error"
        )

        return redirect(
            url_for("notes")
        )


    if not note["file_data"]:

        flash(
            "PDF file is not available.",
            "error"
        )

        return redirect(
            url_for("notes")
        )


    return send_file(
        io.BytesIO(note["file_data"]),
        mimetype="application/pdf",
        as_attachment=True,
        download_name=note["filename"]
    )


# =========================================================
# DELETE NOTE
# =========================================================

@app.route(
    "/delete-note/<int:note_id>"
)
def delete_note(note_id):

    if "user_id" not in session:

        return redirect(
            url_for("login")
        )


    if session.get(
        "user_role"
    ) != "admin":

        flash(
            "Only admin can delete notes.",
            "error"
        )

        return redirect(
            url_for("dashboard")
        )


    connection = get_db()

    try:

        note = connection.execute(
            """
            SELECT id
            FROM notes
            WHERE id = %s
            """,
            (note_id,)
        ).fetchone()


        if note:

            connection.execute(
                """
                DELETE FROM notes
                WHERE id = %s
                """,
                (note_id,)
            )

            connection.commit()

            flash(
                "Note deleted successfully.",
                "success"
            )

        else:

            flash(
                "Note not found.",
                "error"
            )

    finally:

        connection.close()


    return redirect(
        url_for("admin_dashboard")
    )


# =========================================================
# LOGOUT
# =========================================================

@app.route("/logout")
def logout():

    session.clear()

    return redirect(
        url_for("home")
    )


# =========================================================
# RUN APPLICATION
# =========================================================

if __name__ == "__main__":

    app.run(
        debug=True
    )